"""Add NextcloudSettings table

Revision ID: d4f2a1b8e9c3
Revises: ce082c6033de
Create Date: 2025-11-07 20:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f2a1b8e9c3'
down_revision: Union[str, None] = 'ce082c6033de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nextcloud_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_url', sa.String(length=500), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=500), nullable=False),
        sa.Column('base_path', sa.String(length=500), nullable=True),
        sa.Column('auto_sync_enabled', sa.Boolean(), nullable=True),
        sa.Column('sync_on_upload', sa.Boolean(), nullable=True),
        sa.Column('sync_on_rename', sa.Boolean(), nullable=True),
        sa.Column('sync_strategy', sa.String(length=50), nullable=True),
        sa.Column('is_connected', sa.Boolean(), nullable=True),
        sa.Column('last_connection_test', sa.DateTime(timezone=True), nullable=True),
        sa.Column('connection_error', sa.Text(), nullable=True),
        sa.Column('total_synced', sa.Integer(), nullable=True),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nextcloud_settings_id'), 'nextcloud_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nextcloud_settings_id'), table_name='nextcloud_settings')
    op.drop_table('nextcloud_settings')
    # ### end Alembic commands ###
